import assert from "node:assert/strict";
import { mkdtemp, readdir, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { test } from "node:test";
import {
  createTokenStore,
  DotenvTokenStore,
  FileTokenStore,
} from "./token-store.js";

const CREDENTIALS = { refresh_token: "test-refresh-token" };

async function temporaryPath(name = "token.json"): Promise<string> {
  return join(await mkdtemp(join(tmpdir(), "gsc-token-test-")), name);
}

test("writes and loads token files with private permissions", async () => {
  const path = await temporaryPath(join("nested", "token.json"));
  const store = new FileTokenStore(path);
  await store.save(CREDENTIALS);

  assert.equal((await stat(path)).mode & 0o777, 0o600);
  assert.deepEqual(await store.load(), CREDENTIALS);
});

test("overwrites an existing token file", async () => {
  const path = await temporaryPath();
  const store = new FileTokenStore(path);

  await store.save({ refresh_token: "first-refresh-token" });
  await store.save({ refresh_token: "second-refresh-token" });

  assert.deepEqual(await store.load(), {
    refresh_token: "second-refresh-token",
  });
  assert.deepEqual(await readdir(dirname(path)), ["token.json"]);
});

test("reports the authorization action for a missing token file", async () => {
  await assert.rejects(
    new FileTokenStore(await temporaryPath("missing.json")).load(),
    /Run npm run auth first/,
  );
});

test("createTokenStore resolves the configured token file", () => {
  const store = createTokenStore({ GSC_TOKEN_FILE: "/tmp/gsc/token.json" });
  assert.ok(store instanceof FileTokenStore);
  assert.match(store.description, /\/tmp\/gsc\/token\.json/);
});

test("dotenv token store reads the refresh token from the mount", async () => {
  const path = await temporaryPath(".env");
  await writeFile(
    path,
    "# generated by 1Password\nGSC_CLIENT_ID=abc\nGSC_REFRESH_TOKEN=grant-from-vault\n",
  );

  assert.deepEqual(await new DotenvTokenStore(path).load(), {
    refresh_token: "grant-from-vault",
  });
});

test("dotenv token store says what to do when the token is absent", async () => {
  const path = await temporaryPath(".env");
  await writeFile(path, "GSC_CLIENT_ID=abc\n");

  await assert.rejects(
    new DotenvTokenStore(path).load(),
    /Run npm run auth, then add the refresh token/,
  );
});

test("dotenv token store points at the mount when it is missing", async () => {
  await assert.rejects(
    new DotenvTokenStore(await temporaryPath("absent.env")).load(),
    /1Password Environment mount, it is missing/,
  );
});

test("dotenv token store refuses to write, since the mount is read-only", async () => {
  const path = await temporaryPath(".env");
  await writeFile(path, "GSC_REFRESH_TOKEN=grant\n");

  await assert.rejects(
    new DotenvTokenStore(path).save({ refresh_token: "rotated" }),
    /serves reads only/,
  );
});

test("createTokenStore falls back to the credential mount for the token", () => {
  const store = createTokenStore({
    GSC_TOKEN_PROVIDER: "dotenv",
    GSC_SECRET_DOTENV_PATH: "/mnt/gsc/.env",
  });
  assert.ok(store instanceof DotenvTokenStore);
  assert.match(store.description, /GSC_REFRESH_TOKEN in \/mnt\/gsc\/\.env/);
});

test("createTokenStore rejects an unknown token provider", () => {
  assert.throws(
    () => createTokenStore({ GSC_TOKEN_PROVIDER: "vault" }),
    /Unknown GSC_TOKEN_PROVIDER "vault"/,
  );
});
